[toolchain]
anchor_version = "1.0.2"
solana_version = "3.1.14"

[features]
resolution = true
skip-lint = false

[programs.devnet]
helio = "EJw2Y8jJwbw1CeHRDRHSeUYzU2L1ke1aqmkQLod5T151"
mock_yield_vault = "EQXhez36iW9smfarF4oNTGgRa3iL1Nr7KowgPthujqeM"

[programs.localnet]
helio = "EJw2Y8jJwbw1CeHRDRHSeUYzU2L1ke1aqmkQLod5T151"
mock_yield_vault = "EQXhez36iW9smfarF4oNTGgRa3iL1Nr7KowgPthujqeM"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
